# Site settings
title: Sérgio Oliveira - seocam
email: seocam@seocam.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://seocam.com"
twitter_username: seocam
github_username:  seocam 

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
  - jekyll-mentions
